module.exports = {
  home: 'Home',
  welcome: 'Welcome',
  setupUser: 'Setup User',
  getStarted: 'Get Started',
  name: 'Name',
  choosePin: 'Choose PIN',
  confirmPin: 'Confirm PIN',
  createdUser: 'Created User',
  userCreated: 'User Created',
  setupWallet: 'Setup Wallet',
  createWallet: 'Create Wallet',
  proceed: 'Proceed',
  attentionScreen1: 'AttentionScreen1',
  attentionScreen2: 'AttentionScreen2',
  watchSurroundings: 'Watch Your Surroundings',
  attention1Description:
    'Make sure no one is watching you or recording on camera.',
  understand: 'I Understand',
  numberOfWords: 'number of words',
  areUSure: 'Are You Sure?',
  attention2Description:
    'If you go back, you will lose the created seeds and recreate new ones.',
  checkAgain: 'Check Again',
  recoverySeeds: 'Recovery seed',
  attentionScreen3: 'attentionScreen3',
  secureSeeds: 'Did you secure recovery seeds?',
  attention3Description:
    'Please, write the seed words in the correct order and store them in a secure place.',
  confirmSeeds: 'Confirm Seeds',
  complateSeeds: 'Complate Seeds',
  confirm: 'Confirm',
  complate: 'Complete',
  importWallet: 'Import Wallet',
  edit: 'Edit',
  welcomePurchase: 'Welcome Purchase',
  enterPassword: 'Enter Passphrase',
  passphrase: 'Passphrase',
  enter: 'Enter ',
  enterName: 'Name Required',
  enterPIN: 'Pin Required ',
  matchedPIN: 'Pin does not matched',
  enterSeedsCorrectly: 'Did you enter the seeds correctly?',
  hiddenWallet: 'Hidden Wallet',
  main: 'Main',
  connect: 'Connect',
  AboutCODL: 'About CODL',
  language: 'Language',
  networks: 'Networks',
  recoveryCheck: 'Recovery Check',
  changePIN: 'Change PIN',
  changeName: 'Change Name',
  deleteEverything: 'Delete Everything',
  lockDevice: 'Lock Device',
  unlock: 'Unlock',
  enterPin: 'Enter PIN',
  wrongPin: 'Wrong PIN',
  error: 'Error!',
  nameErrorMess: 'Name must be greater than 1 and less than 15 characters.',
  pinErrorMess: 'PIN must be greater than 4 and less than 8 characters.',
  pinMatchError: 'Confirm pin is not correct.',
  ok: 'OK',
  hidden: 'Hidden',
  attemptsLeft: 'Attempts Left',
  tryAgain: 'Try Again',
  lastTry: 'Last Try',
  lastTryDescription: 'if wrong everything will be deleted',
  changeUserDetails: 'changeUserDetails',
  currentPin: 'Current PIN',
  newPin: 'New PIN',
  confirmNewPin: 'Confirm New PIN',
  english: 'English',
  turkce: 'Türkçe',
  done: 'Done',
  terms: 'Terms',
  etc: 'Etc',
  version: 'version',
};
